### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by briansunter** [sapphi-red/typescript-plugin-toml#1]
Hello, I'm having some trouble getting typescript and my IDE to recognize the types in the TOML file.
I'm using typescript 5, and set up the plugin in my tsconfig, as well as using the workspace typescript version.

<img width="537" alt="Screenshot 2023-10-30 at 11 35 49 AM" src="https://github.com/sapphi-red/typescript-plugin-toml/assets/2816289/877a359e-4ce3-4740-90e5-4185c63267d1">

I reproduced the issue here. Even though I get a type error it does work with the toml vite plugin.

https://github.com/briansunter/toml-import

**Comment by sapphi-red** [comment]
I've released v0.3.1 with the fix for TS 5.0+. Let me know if it still doesn't work.

**Comment by briansunter** [comment]
Works perfectly now. Thank you!
